apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-redis-pv
  namespace: {{ .Release.Namespace }}
  labels:
    pv: redis
spec:
  capacity:
    {{- if and "exists" .Values.redis.storage }}
    storage: {{ .Values.redis.storage }}
    {{- else }}
    storage: 500Mi
    {{- end }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.ip }}
