{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ingree-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- (.Files.Glob "cert/*").AsSecrets | nindent 2}}
{{- end }}
{{- end }}

