apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-headless-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-server-headless-service
spec:
  ports:
  - port: 80
    targetPort: 80
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-server