{{ $name := .Release.Name }}
{{ $nameSpace := .Release.Namespace }}
{{ $server := .Values.server }}
{{ $path := .Values.hostPath.server.path }}
{{- range .Values.server.index }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ $name }}-server{{ . }}-deployment
  namespace: {{ $nameSpace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $name }}-server{{ . }}
    spec:
      volumes:
      - name: server-data
        hostPath:
          path: {{ $path }}{{ . }}/root
      - name: server-temp
        hostPath:
          path: {{ $path }}{{ . }}/tmp
      - name: server-logs
        hostPath:
          path: {{ $path }}{{ . }}/logs
      containers:
      - name: {{ $name }}-server
        image: {{ $server.image.name }}:{{ $server.image.version }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: server-data
          mountPath: /logs
        - name: server-temp
          mountPath: /root
        - name: server-logs
          mountPath: /tmp
        ports:
        - containerPort: 80
        env:
        - name: SignalUrl
          value: /server/signal
        - name: StorageUrl
          value: /data/shard
        - name: StorageChuckUrl
          value: /data/chuck
        - name: Token
          value: {{ $server.token | default "9u0c8ehbqu23j9ur20fe8yqs9ijo3h2r9uu" | quote }}
        - name: Key
          value: {{ $server.key | default "Resendqwegkoiju8024r9u3j" | quote }}
        - name: Resend
          value: {{ $server.resend | default "3" | quote }}
        - name: Gzip
          value: {{ $server.gzip | default "false" | quote }}
        - name: ServerIp
          value: {{ range $server.index }}{{ $name }}-server{{ . }},{{ end }}
        - name: DataShards
          value: {{ $server.datashards | default "4" | quote }}
        - name: ParityShards
          value: {{ $server.parityshards | default "2" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-server{{ . }}-service
  namespace: {{ $nameSpace }}
spec:
  selector:
    app: {{ $name }}-server{{ . }}
  ports:
    - port: 80
      targetPort: 80
{{- end }}