apiVersion: v1
kind: Service
metadata:
  name: liuma-mongo-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-mongo
  ports:
    - port: 27017
      targetPort: 27017