apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongo-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {{- if and "exists" .Values.mongo.storage }}
      storage: {{ .Values.mongo.storage }}
      {{- else }}
      storage: 1Gi
      {{- end }}
  storageClassName: ""
  selector:
    pv: mongo